on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: echo "Alejandro Gras Olea"
      - run: node --version      
      - run: echo "IS-726598"
      - uses: actions/checkout@v3
